### ISSUE TITLE
Fix user join handling

### ISSUE THREAD

**Issue by Ethazeriel** [Ethazeriel/discord-bot#147]
specifically, it appears broken when a user who is already a member of a guild joins a different guild.
as far as I can tell, the issue is that we only create the user if they're truly new; we don't add the separate guild section for the new nickname for this specific circumstance, which is what I believed caused the crash we noted on november 5th.

there's some conflict between client.on guildmemberadd and client.on userupdate, but I think most importantly guildmemberadd needs an else if the user already exists.

**Comment by Ethazeriel** [comment]
![image](https://github.com/Ethazeriel/discord-bot/assets/10165790/e0e6deea-983e-4f3e-933e-74d76ed32c74)

**Comment by Whuppee** [comment]
seems fixed
